version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v4.1.0
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
      - ./build/middleware:/opt/tyk-gateway/middleware
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
      - tyk-bundles
  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - 6379:6379
  tyk-bundles:
    image: nginxinc/nginx-unprivileged:1.21.6-alpine
    networks:
      - tyk
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - 8082:8080

networks:
  tyk: