version: '3.3'
services:

  my-service:
    image: my-service:1.0.0
    networks:
      - mynetwork
    environment:
      - REDIS_ADDRESS=myredis:6379
    ports:
      - "8080:8080"

  my-redis:
    image: redis:5.0-alpine
    networks:
      - mynetwork
    ports:
      - "6379:6379"


networks:
  mynetwork:
