version: '3.3'

services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v4.2.0
    ports:
      - "8080:8080"
    networks:
      - tyk
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
    environment:
      - TYK_GW_SECRET=foo
  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - "6379:6379"

networks:
  tyk: